const mongoose=require('mongoose');

const QuestionHeader=new mongoose.Schema({
    medium:{
        type:String
    },
    classs:{
        type:String
    },
    subject:{
        type:String
    },
    marks:{
        type:String
    },
    time:{
        type:String
    },
    studentinfo:{
        type:String
    },
    examdate:{
        type:String
    },
    totalquestion:{
        type:String
    },
    nameofstudent:{
        type:String
    },
    satsno:{
        type:String
    },
    signature:{
        type:String
    },
    roominvigilator:{
        type:String
    },
    idsccode:{
        type:String
    },
    schoolname:{
        type:String
    },
    cluster:{
        type:String
    },
    block:{
        type:String
    },
    distric:{
        type:String
    } ,
    govt:{
        type:String
    },
    aided:{
        type:String
    },
    unaided:{
        type:String
    },
    markinfo:{
        type:String
    },
    signatureinvigilator:{
        type:String
    },
    evaluator:{
        type:String
    },
    questionno1:{
        type:String
    },
    obtainedno1:{
        type:String
    },
    questionno2:{
        type:String
    },
    obtainedno2:{
        type:String
    },
    questionno3:{
        type:String
    },
    obtainedno3:{
        type:String
    },
    totalmarks1:{
        type:String
    },
    totalmarks2:{
        type:String
    },
    totalmarks3:{
        type:String
    },
    grandtotal:{
        type:String
    },
    totalobtainedmarks:{
        type:String
    },
    evaluatorsign:{
        type:String
    }, 
    ans:{
        type:String
    },
    or:{
        type:String
    },
    answerheader:{
        type:String
    },
    mediumHead:{
        type:String
    },
    lastSign:{
        type:String
    },
    blueprintBoard:{
        type:String
    },
    
},{timestamps:true});
module.exports=mongoose.model("questionheader",QuestionHeader);
